name: pod_pulse
description: "A unique Software-as-a-Service podcast app with AI-powered features like text-to-multiple-voices functionality and AI-generated images"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  keyboard_dismisser: ^3.0.0
  rmdev_widgets:
    path: /Users/Rychid/Documents/projects/personal/mobile/packages/rmdev_widgets
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/
     - assets/animations/
     - assets/audios/


